### PR TITLE
Added `map`

### PR DESCRIPTION
**Pull request by taphu**
See commits for comments.

### CODE REVIEW

**Comment by glasserc** [comment]
I've been thinking about this on and off for a while. It would be nice if we could provide ``Functor`` and even ``Monad`` instances for ``LoadBalanced``, so you could write e.g.

```
-- | Let's say there's a cluster of some service with exactly one endpoint.
fetchArbitrary :: LoadBalanced URL -> LoadBalanced Response
fetchArbitrary urls = do
    url <- urls
    liftIO $ httpLbs (makeRequest url)
```

I guess the above example requires ``MonadIO`` too, which might or might not be a good idea. In terms of implementation, the best I could do was to carry along a "sidecar" ``a -> IO b`` and have all access to ``LoadBalanced`` run through that sidecar. But it's not elegant. Note that the underlying ``Set`` doesn't implement ``Functor``, and indeed ``Set.map`` might not behave the way you expect because its output might have fewer elements than its input.

I feel like the fact that stuff like this is hard is a hint that we chose a bad structure when we implemented ``LoadBalanced``. Maybe there is a better underlying monad. I've been meaning to look into it, but it hasn't been a priority.

**Comment by potomak** [comment]
I'd like to understand better why @taphu

> can't figure out how to make a compatible `instance Functor`

Question: could you *fmap* over a `LoadBalanced a` by just *fmapping* the function over the `IO (Set a)` instead of creating also a new queue?

At the first `withResource` invocation the queue would be updated by `updateTargets` and resource bindings for resources that are no longer present in the `Set` would be removed.

**Comment by pjrt** [comment]
@potomak I think the issue is the `psQuereT`. I'm not familiar with this type (LoadBalanced) or why it is used but having that `PSQ a` [which is not a functor](http://hackage.haskell.org/package/PSQueue-1.1/docs/Data-PSQueue.html#t:PSQ) would make this impossible to turn into a functor (unless we can actually make a functor out of it and the lib author just missed that).

**Comment by potomak** [comment]
@pjrt correct me if I'm wrong, but I think the real problem™ is that `psQuereT` is a `TVar` that needs to be created *atomically*.

About the naming issue: I think "map" is a good name for this function, but then we should always import it *qualified*. That would be almost the same as adding a suffix to the function name. For this reason I like "map" more than "mapLB" or "mapLoadbalance".

**Comment by pjrt** [comment]
@potomak Oh, that is another issue. Yeah, so there are 2 reasons: PSQ cannot be mapped and neither can a TVar. 

About naming, my main issue with "map" is that it is usually a function that `fmap` points to (`fmap = map` in a lot of cases). This can lead to people thinking "oh, LB has a `map`, so it must be a functor".

**Comment by potomak** [comment]
The fact that `PSQ a` is not an instance of `Functor` is not a problem at all because, if it wouldn't be a `TVar`, in `fmap` we could just create a new queue as @taphu did in his `map` implementation.

I think that the alternative names you proposed didn't change the problem, that's why I think "map" is a good enough name for the function.

**Comment by pjrt** [comment]
Ah, didn't noticed that the original PSQ is thrown out. Then yeah, the TVar is the issue.

**Pull request merged**
